server:
  port: 8080
spring:
  application:
    name: "ms-stats"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  rabbitmq:
    connection-timeout: 10000
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    virtual-host: "/"
    maxPriority: 50
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5s
          max-attempts: 3
          max-interval: 10s
          multiplier: 2
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
broker:
  exchanges:
    stats: "stats-exchange"
  queues:
    sofkianoChanges: "sofkiano-changes"
    sofkianoChangesDLQ: "sofkiano-changes-dlq"
  routingKeys:
    sofkianoChanges: "sofkiano.command.changes"
    sofkianoChangesError: "sofkiano.error.changes"