server:
  port: 8080
spring:
  application:
    name: "people"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://${people_database_url}/${people_database_name}"
    username: "${people_database_username}"
    password: "${people_database_password}"
    driverClassName: "org.postgresql.Driver"
    platform: "postgres"
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 900000
  jpa:
    database: "POSTGRESQL"
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
